import type { KnowledgeNode, PracticeSet, QuestionBankItem } from './types';

let idCounter = 0;
function genId(prefix: string): string {
  idCounter++;
  return `${prefix}_${idCounter}_${Date.now()}`;
}

export function createId(prefix = 'node'): string {
  return genId(prefix);
}

export const SAMPLE_MIND_MAP: KnowledgeNode = {
  id: 'root_1',
  name: '行测',
  type: 'subject',
  content: '行政职业能力测验，简称行测，是公务员考试笔试公共科目之一，主要测查与公务员职业密切相关的、适合通过客观化纸笔测验方式进行考查的基本素质和能力要素。',
  annotation: '行测一般为120分钟，130-135题，时间紧任务重',
  questions: [],
  children: [
    {
      id: 'k_1',
      name: '言语理解与表达',
      type: 'knowledge',
      content: '主要测查运用语言文字进行思考和交流、迅速准确地理解和把握文字材料内涵的能力。',
      questions: [],
      children: [
        {
          id: 'sk_1',
          name: '片段阅读',
          type: 'subknowledge',
          content: '给定一段文字，要求根据文字内容回答问题，常见题型包括主旨概括、意图判断、细节理解等。',
          annotation: '做题技巧：先看问题，再读文段，找关键句',
          questions: [],
          children: [
            {
              id: 'a_1',
              name: '主旨概括题',
              type: 'angle',
              content: '要求概括文段的主旨或中心思想。常见提问方式："这段文字主要说明/讲述/讨论的是""对这段文字概括最准确的是"。',
              annotation: '关键：找主题句，注意转折词、总结词后的内容',
              questions: [
                {
                  id: 'q_1',
                  content: '在宋明理学中，"格物致知"的"格物"二字，最准确的理解是：',
                  options: [
                    { label: 'A', text: '推究事物之理' },
                    { label: 'B', text: '抵御外物诱惑' },
                    { label: 'C', text: '观察事物表象' },
                    { label: 'D', text: '感受事物变化' },
                  ],
                  correctAnswer: 'A',
                  explanation: '"格物"在宋明理学中意为推究事物之理，是认识论的核心概念。朱熹强调通过穷尽事物之理来获取知识。',
                  images: [],
                },
                {
                  id: 'q_2',
                  content: '这段文字意在说明：\n"文化是一个国家、一个民族的灵魂。历史和现实都表明，一个抛弃了或者背叛了自己历史文化的民族，不仅不可能发展起来，而且很可能上演一场历史悲剧。"',
                  options: [
                    { label: 'A', text: '文化的重要性' },
                    { label: 'B', text: '历史的教训' },
                    { label: 'C', text: '民族的发展' },
                    { label: 'D', text: '文化多元化' },
                  ],
                  correctAnswer: 'A',
                  explanation: '文段核心围绕"文化是灵魂"展开，强调文化对民族的重要性，属于主旨概括题的典型解题思路。',
                  images: [],
                },
              ],
              children: [],
            },
            {
              id: 'a_2',
              name: '意图判断题',
              type: 'angle',
              content: '要求判断作者的意图或目的。常见提问方式："这段文字意在强调/说明/表明""作者通过这段文字最想传达的是"。',
              annotation: '注意区分"意图"与"主旨"：意图更偏向言外之意',
              questions: [
                {
                  id: 'q_3',
                  content: '作家写作时，总想把自己的思想融入作品，但过于直白地表达观点，反而会让读者产生抵触心理。因此，高明的作家往往通过含蓄的方式传递思想。这段话意在强调：',
                  options: [
                    { label: 'A', text: '作家不应该在作品中表达思想' },
                    { label: 'B', text: '含蓄表达思想效果更好' },
                    { label: 'C', text: '读者不喜欢有思想的作品' },
                    { label: 'D', text: '直白表达是写作的大忌' },
                  ],
                  correctAnswer: 'B',
                  explanation: '文段通过对比直白表达和含蓄表达的效果，意在强调含蓄表达思想的优越性，B项最符合作者意图。',
                },
              ],
              children: [],
            },
          ],
        },
        {
          id: 'sk_2',
          name: '逻辑填空',
          type: 'subknowledge',
          content: '在文段中填入最恰当的词语，考查实词、成语、虚词的辨析能力。',
          questions: [],
          children: [
            {
              id: 'a_3',
              name: '实词辨析',
              type: 'angle',
              content: '辨析近义实词的细微差别，包括词义轻重、范围大小、感情色彩、搭配习惯等维度。',
              questions: [
                {
                  id: 'q_4',
                  content: '面对复杂多变的国际形势，我们必须保持清醒的头脑，_______地分析和处理问题。',
                  options: [
                    { label: 'A', text: '冷静' },
                    { label: 'B', text: '寂静' },
                    { label: 'C', text: '清静' },
                    { label: 'D', text: '安静' },
                  ],
                  correctAnswer: 'A',
                  explanation: '"冷静"指沉着、不感情用事，与"保持清醒的头脑"搭配最恰当。"寂静""清静""安静"均侧重安静无声，不符合语境。',
                },
              ],
              children: [],
            },
            {
              id: 'a_4',
              name: '成语辨析',
              type: 'angle',
              content: '辨析常见成语的含义、适用对象、感情色彩、近义成语的区别。高频成语约200个。',
              annotation: '常考成语：独树一帜、标新立异、别出心裁、另起炉灶、不落窠臼等',
              questions: [
                {
                  id: 'q_5',
                  content: '他在学术研究上_______，从不人云亦云，总能提出独到的见解。',
                  options: [
                    { label: 'A', text: '独树一帜' },
                    { label: 'B', text: '标新立异' },
                    { label: 'C', text: '别出心裁' },
                    { label: 'D', text: '另起炉灶' },
                  ],
                  correctAnswer: 'A',
                  explanation: '"独树一帜"指自成一家，与"不人云亦云""独到见解"呼应，强调独特性。"标新立异"偏向故意不同，"别出心裁"偏重设计，"另起炉灶"指重新开始。',
                },
              ],
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 'k_2',
      name: '数量关系',
      type: 'knowledge',
      content: '主要测查理解、把握事物间量化关系和解决数量关系问题的能力，包括数据关系的分析、推理、判断、运算等。',
      questions: [],
      children: [
        {
          id: 'sk_3',
          name: '数学运算',
          type: 'subknowledge',
          questions: [],
          children: [
            {
              id: 'a_5',
              name: '行程问题',
              type: 'angle',
              content: '研究速度、时间和路程三者关系的问题。核心公式：路程=速度×时间。常见题型：相遇问题、追及问题、流水行船问题。',
              annotation: '行程问题公式图解可帮助理解',
              images: ['https://placehold.co/400x200/e8f4f8/333?text=行程问题+公式%3A+S%3DV×T'],
              questions: [
                {
                  id: 'q_6',
                  content: '甲、乙两人从A、B两地同时出发相向而行，甲的速度是60公里/小时，乙的速度是40公里/小时。两人在距A地180公里处相遇，则A、B两地相距多少公里？',
                  options: [
                    { label: 'A', text: '280' },
                    { label: 'B', text: '300' },
                    { label: 'C', text: '320' },
                    { label: 'D', text: '360' },
                  ],
                  correctAnswer: 'B',
                  explanation: '甲行180公里用时180÷60=3小时。乙行40×3=120公里。总距离=180+120=300公里。',
                },
              ],
              children: [],
            },
            {
              id: 'a_6',
              name: '工程问题',
              type: 'angle',
              content: '研究工作效率、工作时间和工作量三者关系的问题。核心思路：设工作总量为1（或最小公倍数），用效率的倒数表示时间。',
              images: ['https://placehold.co/400x200/fef3c7/333?text=工程问题+总量%3D效率×时间'],
              questions: [
                {
                  id: 'q_7',
                  content: '一项工程，甲单独做需12天完成，乙单独做需18天完成。甲、乙合作3天后，剩下的由乙单独完成，还需多少天？',
                  options: [
                    { label: 'A', text: '4.5天' },
                    { label: 'B', text: '5天' },
                    { label: 'C', text: '6天' },
                    { label: 'D', text: '7.5天' },
                  ],
                  correctAnswer: 'D',
                  explanation: '甲效率1/12，乙效率1/18。合作3天完成3×(1/12+1/18)=3×5/36=5/12。剩余7/12，乙单独需(7/12)÷(1/18)=7/12×18=10.5天，但3天已做，还需10.5-3=7.5天。实际计算：剩余7/12÷(1/18)=7×18/12=10.5天。注意这里合作3天已含在内，剩余=1-5/12=7/12，乙需7/12÷(1/18)=10.5天完成剩余部分。',
                },
              ],
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 'k_3',
      name: '判断推理',
      type: 'knowledge',
      content: '主要测查对各种事物关系的分析推理能力，包括图形推理、定义判断、类比推理、逻辑判断等。',
      questions: [],
      children: [
        {
          id: 'sk_4',
          name: '图形推理',
          type: 'subknowledge',
          questions: [],
          children: [
            {
              id: 'a_7',
              name: '位置规律',
              type: 'angle',
              questions: [
                {
                  id: 'q_8',
                  content: '一组图形中，黑色方块依次向右移动一格，到最右端后从左侧重新出现，这属于哪种规律？',
                  options: [
                    { label: 'A', text: '平移规律' },
                    { label: 'B', text: '旋转规律' },
                    { label: 'C', text: '翻转规律' },
                    { label: 'D', text: '叠加规律' },
                  ],
                  correctAnswer: 'A',
                  explanation: '黑色方块沿水平方向依次移动，到边界后循环出现，属于典型的平移规律。',
                },
              ],
              children: [],
            },
          ],
        },
        {
          id: 'sk_5',
          name: '逻辑判断',
          type: 'subknowledge',
          questions: [],
          children: [
            {
              id: 'a_8',
              name: '削弱论证',
              type: 'angle',
              questions: [
                {
                  id: 'q_9',
                  content: '某研究显示，每天喝咖啡的人患心脏病的概率低于不喝咖啡的人。因此，喝咖啡有助于预防心脏病。以下哪项如果为真，最能削弱上述论证？',
                  options: [
                    { label: 'A', text: '喝咖啡的人通常也注重锻炼' },
                    { label: 'B', text: '咖啡的种类不同效果不同' },
                    { label: 'C', text: '有些人喝咖啡会失眠' },
                    { label: 'D', text: '心脏病有遗传因素' },
                  ],
                  correctAnswer: 'A',
                  explanation: 'A项指出存在他因（锻炼），可能是锻炼而非咖啡降低了心脏病风险，属于他因削弱，最能削弱原论证的因果关系。',
                },
              ],
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 'k_4',
      name: '资料分析',
      type: 'knowledge',
      questions: [],
      children: [
        {
          id: 'sk_6',
          name: '增长率计算',
          type: 'subknowledge',
          questions: [],
          children: [
            {
              id: 'a_9',
              name: '同比/环比增长',
              type: 'angle',
              content: '同比增长率=(本期数-上年同期数)/上年同期数×100%；环比增长率=(本期数-上期数)/上期数×100%。',
              annotation: '注意区分同比（与去年同期比）和环比（与上一时期比）',
              images: ['https://placehold.co/400x200/dcfce7/333?text=增长率公式%3A+%28本期-基期%29÷基期'],
              questions: [
                {
                  id: 'q_10',
                  content: '2023年某市GDP为8000亿元，2022年为7200亿元，则该市GDP同比增长率为：',
                  options: [
                    { label: 'A', text: '10.0%' },
                    { label: 'B', text: '11.1%' },
                    { label: 'C', text: '12.5%' },
                    { label: 'D', text: '8.0%' },
                  ],
                  correctAnswer: 'B',
                  explanation: '同比增长率=(8000-7200)/7200×100%=800/7200×100%≈11.1%。',
                },
              ],
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 'k_5',
      name: '常识判断',
      type: 'knowledge',
      questions: [],
      children: [
        {
          id: 'sk_7',
          name: '政治常识',
          type: 'subknowledge',
          questions: [],
          children: [
            {
              id: 'a_10',
              name: '习近平新时代中国特色社会主义思想',
              type: 'angle',
              questions: [
                {
                  id: 'q_11',
                  content: '习近平新时代中国特色社会主义思想的核心要义是：',
                  options: [
                    { label: 'A', text: '坚持和发展中国特色社会主义' },
                    { label: 'B', text: '全面深化改革' },
                    { label: 'C', text: '全面依法治国' },
                    { label: 'D', text: '全面从严治党' },
                  ],
                  correctAnswer: 'A',
                  explanation: '坚持和发展中国特色社会主义是习近平新时代中国特色社会主义思想的核心要义。',
                },
              ],
              children: [],
            },
          ],
        },
        {
          id: 'sk_8',
          name: '法律常识',
          type: 'subknowledge',
          questions: [],
          children: [
            {
              id: 'a_11',
              name: '宪法',
              type: 'angle',
              questions: [
                {
                  id: 'q_12',
                  content: '根据我国宪法，中华人民共和国的一切权力属于：',
                  options: [
                    { label: 'A', text: '人民' },
                    { label: 'B', text: '公民' },
                    { label: 'C', text: '人民代表大会' },
                    { label: 'D', text: '国家机关' },
                  ],
                  correctAnswer: 'A',
                  explanation: '《宪法》第二条规定：中华人民共和国的一切权力属于人民。',
                },
              ],
              children: [],
            },
          ],
        },
      ],
    },
  ],
};

export const SAMPLE_PRACTICE_SETS: PracticeSet[] = [
  {
    id: 'ps_1',
    name: '行测真题模拟卷一',
    createdAt: '2024-06-01T00:00:00.000Z',
    questions: [
      {
        id: 'pq_1',
        content: '"绿水青山就是金山银山"这一理念体现了：',
        options: [
          { label: 'A', text: '经济发展与生态保护的辩证统一' },
          { label: 'B', text: '生态保护优先于经济发展' },
          { label: 'C', text: '经济发展可以牺牲环境' },
          { label: 'D', text: '环境保护与经济无关' },
        ],
        correctAnswer: 'A',
        explanation: '该理念体现了经济发展与生态保护的辩证统一关系，不是非此即彼的对立关系。',
        linkedAngleId: 'a_10',
        linkedAngleName: '习近平新时代中国特色社会主义思想',
      },
      {
        id: 'pq_2',
        content: '甲、乙两车同时从A地出发前往B地，甲车速度80km/h，乙车速度60km/h。甲车到达B地后立即返回，在距B地40km处与乙车相遇。A、B两地相距：',
        options: [
          { label: 'A', text: '200km' },
          { label: 'B', text: '240km' },
          { label: 'C', text: '280km' },
          { label: 'D', text: '300km' },
        ],
        correctAnswer: 'C',
        explanation: '设AB距离为S。相遇时甲走S+40，乙走S-40。时间相等：(S+40)/80=(S-40)/60，解得S=280km。',
        linkedAngleId: 'a_5',
        linkedAngleName: '行程问题',
      },
      {
        id: 'pq_3',
        content: '下列关于我国宪法表述正确的是：',
        options: [
          { label: 'A', text: '宪法是国家的根本法' },
          { label: 'B', text: '宪法具有最高的法律效力' },
          { label: 'C', text: '宪法的修改由全国人大以全体代表三分之二以上多数通过' },
          { label: 'D', text: '以上都对' },
        ],
        correctAnswer: 'D',
        explanation: '宪法是国家的根本法，具有最高法律效力，其修改需全国人大全体代表三分之二以上多数通过，三个表述均正确。',
        linkedAngleId: 'a_11',
        linkedAngleName: '宪法',
      },
      {
        id: 'pq_4',
        content: '某企业2023年利润为500万元，2022年为400万元，则利润同比增长：',
        options: [
          { label: 'A', text: '20%' },
          { label: 'B', text: '25%' },
          { label: 'C', text: '30%' },
          { label: 'D', text: '50%' },
        ],
        correctAnswer: 'B',
        explanation: '同比增长率=(500-400)/400×100%=25%。',
        linkedAngleId: 'a_9',
        linkedAngleName: '同比/环比增长',
      },
      {
        id: 'pq_5',
        content: '面对困境，他不但没有退缩，反而_______地迎难而上。填入画横线部分最恰当的是：',
        options: [
          { label: 'A', text: '毅然' },
          { label: 'B', text: '仍然' },
          { label: 'C', text: '忽然' },
          { label: 'D', text: '显然' },
        ],
        correctAnswer: 'A',
        explanation: '"毅然"指坚决地、毫不犹豫地，与"没有退缩""迎难而上"语境最吻合。',
        linkedAngleId: 'a_3',
        linkedAngleName: '实词辨析',
      },
    ],
  },
];

// --- Question Bank: unified bank of all questions, categorized by knowledge path ---
export const SAMPLE_QUESTION_BANK: QuestionBankItem[] = [
  // ===== 言语理解与表达 - 片段阅读 - 主旨概括题 (a_1) =====
  {
    id: 'qb_1',
    content: '在宋明理学中，"格物致知"的"格物"二字，最准确的理解是：',
    options: [
      { label: 'A', text: '推究事物之理' },
      { label: 'B', text: '抵御外物诱惑' },
      { label: 'C', text: '观察事物表象' },
      { label: 'D', text: '感受事物变化' },
    ],
    correctAnswer: 'A',
    explanation: '"格物"在宋明理学中意为推究事物之理，是认识论的核心概念。朱熹强调通过穷尽事物之理来获取知识。',
    linkedAngleId: 'a_1',
    linkedAngleName: '主旨概括题',
    knowledgePath: '行测/言语理解与表达/片段阅读/主旨概括题',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_2',
    content: '这段文字意在说明：\n"文化是一个国家、一个民族的灵魂。历史和现实都表明，一个抛弃了或者背叛了自己历史文化的民族，不仅不可能发展起来，而且很可能上演一场历史悲剧。"',
    options: [
      { label: 'A', text: '文化的重要性' },
      { label: 'B', text: '历史的教训' },
      { label: 'C', text: '民族的发展' },
      { label: 'D', text: '文化多元化' },
    ],
    correctAnswer: 'A',
    explanation: '文段核心围绕"文化是灵魂"展开，强调文化对民族的重要性，属于主旨概括题的典型解题思路——找中心句。',
    linkedAngleId: 'a_1',
    linkedAngleName: '主旨概括题',
    knowledgePath: '行测/言语理解与表达/片段阅读/主旨概括题',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_3',
    content: '"随着互联网技术的飞速发展，传统媒体面临着前所未有的挑战。然而，挑战与机遇并存，传统媒体若能积极拥抱变革，借助新技术实现转型升级，便能在新时代焕发新的活力。"这段文字的主旨是：',
    options: [
      { label: 'A', text: '传统媒体面临严峻挑战' },
      { label: 'B', text: '互联网技术对传统媒体的冲击' },
      { label: 'C', text: '传统媒体应积极转型升级以应对挑战' },
      { label: 'D', text: '新媒体将完全取代传统媒体' },
    ],
    correctAnswer: 'C',
    explanation: '文段虽先说挑战，但转折词"然而"之后是重点——传统媒体应积极拥抱变革实现转型升级。主旨概括题需关注转折后的内容。',
    linkedAngleId: 'a_1',
    linkedAngleName: '主旨概括题',
    knowledgePath: '行测/言语理解与表达/片段阅读/主旨概括题',
    source: 'upload',
    createdAt: '2024-01-15',
  },
  {
    id: 'qb_100',
    content: '"如果说知识贫穷是一种不幸，那么知识富有是否就一定幸福呢？未必。拥有知识并不等于拥有智慧，也不等于拥有快乐。知识的积累如果缺乏正确的价值导向，反而可能成为危害社会的工具。"对这段话概括最准确的是：',
    options: [
      { label: 'A', text: '知识富有不一定幸福' },
      { label: 'B', text: '知识积累需要正确的价值导向' },
      { label: 'C', text: '知识贫穷是一种不幸' },
      { label: 'D', text: '知识与智慧、快乐无关' },
    ],
    correctAnswer: 'B',
    explanation: '文段层层递进，从"知识富有不一定幸福"到"缺乏正确价值导向反而危害社会"，核心论点是知识积累需要正确的价值导向。',
    linkedAngleId: 'a_1',
    linkedAngleName: '主旨概括题',
    knowledgePath: '行测/言语理解与表达/片段阅读/主旨概括题',
    source: 'upload',
    createdAt: '2024-02-01',
  },

  // ===== 言语理解与表达 - 片段阅读 - 意图判断题 (a_2) =====
  {
    id: 'qb_4',
    content: '作家写作时，总想把自己的思想融入作品，但过于直白地表达观点，反而会让读者产生抵触心理。因此，高明的作家往往通过含蓄的方式传递思想。这段话意在强调：',
    options: [
      { label: 'A', text: '含蓄表达比直白表达更好' },
      { label: 'B', text: '作家不应该表达自己的观点' },
      { label: 'C', text: '读者不喜欢直白的写作方式' },
      { label: 'D', text: '写作应当追求思想的深度' },
    ],
    correctAnswer: 'A',
    explanation: '文段通过对比直白与含蓄两种方式，强调含蓄表达的优越性，意图判断需把握作者倾向。',
    linkedAngleId: 'a_2',
    linkedAngleName: '意图判断题',
    knowledgePath: '行测/言语理解与表达/片段阅读/意图判断题',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_5',
    content: '近年来，不少城市开始推行垃圾分类制度，但在实际操作中仍面临诸多困难。有专家指出，垃圾分类的关键在于公众意识的培养，而非单纯依赖制度约束。这段话意在强调：',
    options: [
      { label: 'A', text: '垃圾分类制度不够完善' },
      { label: 'B', text: '公众意识比制度约束更重要' },
      { label: 'C', text: '垃圾分类应该完全靠自觉' },
      { label: 'D', text: '制度约束在垃圾分类中没有作用' },
    ],
    correctAnswer: 'B',
    explanation: '专家观点明确指出"关键在于公众意识的培养，而非单纯依赖制度约束"，强调公众意识的重要性。',
    linkedAngleId: 'a_2',
    linkedAngleName: '意图判断题',
    knowledgePath: '行测/言语理解与表达/片段阅读/意图判断题',
    source: 'upload',
    createdAt: '2024-01-20',
  },
  {
    id: 'qb_101',
    content: '"某市图书馆的藏书量十年间增长了3倍，但到馆读者人数却下降了40%。图书馆负责人表示，电子阅读的普及是主要原因。"这段话意在说明：',
    options: [
      { label: 'A', text: '图书馆藏书量增长迅速' },
      { label: 'B', text: '电子阅读对传统图书馆造成了冲击' },
      { label: 'C', text: '人们不再喜欢读书' },
      { label: 'D', text: '图书馆应该减少藏书量' },
    ],
    correctAnswer: 'B',
    explanation: '文段呈现藏书增长但读者下降的对比，负责人指出原因是电子阅读普及，意图在于说明电子阅读对传统图书馆的冲击。',
    linkedAngleId: 'a_2',
    linkedAngleName: '意图判断题',
    knowledgePath: '行测/言语理解与表达/片段阅读/意图判断题',
    source: 'upload',
    createdAt: '2024-02-05',
  },

  // ===== 言语理解与表达 - 逻辑填空 - 实词辨析 (a_3) =====
  {
    id: 'qb_6',
    content: '面对困境，他不但没有退缩，反而_______地迎难而上。填入画横线部分最恰当的是：',
    options: [
      { label: 'A', text: '毅然' },
      { label: 'B', text: '仍然' },
      { label: 'C', text: '忽然' },
      { label: 'D', text: '显然' },
    ],
    correctAnswer: 'A',
    explanation: '"毅然"指坚决地、毫不犹豫地，与"没有退缩""迎难而上"语境最吻合。',
    linkedAngleId: 'a_3',
    linkedAngleName: '实词辨析',
    knowledgePath: '行测/言语理解与表达/逻辑填空/实词辨析',
    source: 'practice',
    createdAt: '2024-02-01',
  },
  {
    id: 'qb_7',
    content: '_______的秋风吹过田野，金黄的稻穗随风摇曳。填入画横线部分最恰当的是：',
    options: [
      { label: 'A', text: '萧瑟' },
      { label: 'B', text: '凛冽' },
      { label: 'C', text: '和煦' },
      { label: 'D', text: '凛然' },
    ],
    correctAnswer: 'A',
    explanation: '"萧瑟"形容秋风凄凉冷落，与下文"金黄的稻穗"的秋收景象搭配最恰当。"凛冽"形容冬天寒风，"和煦"形容春风，"凛然"形容严肃令人敬畏。',
    linkedAngleId: 'a_3',
    linkedAngleName: '实词辨析',
    knowledgePath: '行测/言语理解与表达/逻辑填空/实词辨析',
    source: 'upload',
    createdAt: '2024-02-10',
  },
  {
    id: 'qb_102',
    content: '城市的发展不应以_______环境为代价，而应在保护中发展，在发展中保护。填入画横线部分最恰当的是：',
    options: [
      { label: 'A', text: '牺牲' },
      { label: 'B', text: '损坏' },
      { label: 'C', text: '毁坏' },
      { label: 'D', text: '破坏' },
    ],
    correctAnswer: 'A',
    explanation: '"牺牲"暗含为某种目的而主动放弃，与"以……为代价"搭配最恰当，语义也最贴切。"损坏""毁坏"侧重意外，"破坏"侧重故意损害。',
    linkedAngleId: 'a_3',
    linkedAngleName: '实词辨析',
    knowledgePath: '行测/言语理解与表达/逻辑填空/实词辨析',
    source: 'upload',
    createdAt: '2024-02-15',
  },

  // ===== 言语理解与表达 - 逻辑填空 - 成语辨析 (a_4) =====
  {
    id: 'qb_8',
    content: '他在学术研究中_______，终于取得了突破性成果。填入画横线部分最恰当的是：',
    options: [
      { label: 'A', text: '孜孜不倦' },
      { label: 'B', text: '敷衍塞责' },
      { label: 'C', text: '半途而废' },
      { label: 'D', text: '得过且过' },
    ],
    correctAnswer: 'A',
    explanation: '"孜孜不倦"指勤奋努力不知疲倦，与"终于取得突破性成果"的逻辑因果一致。',
    linkedAngleId: 'a_4',
    linkedAngleName: '成语辨析',
    knowledgePath: '行测/言语理解与表达/逻辑填空/成语辨析',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_9',
    content: '这部电影的情节_______，让人看得目不转睛。填入画横线部分最恰当的是：',
    options: [
      { label: 'A', text: '跌宕起伏' },
      { label: 'B', text: '平淡无奇' },
      { label: 'C', text: '索然无味' },
      { label: 'D', text: '千篇一律' },
    ],
    correctAnswer: 'A',
    explanation: '"跌宕起伏"形容事物起伏变化大，与"目不转睛"的关注度一致。其他选项为贬义，与语境不符。',
    linkedAngleId: 'a_4',
    linkedAngleName: '成语辨析',
    knowledgePath: '行测/言语理解与表达/逻辑填空/成语辨析',
    source: 'upload',
    createdAt: '2024-02-15',
  },
  {
    id: 'qb_103',
    content: '近年来，一些商家为了追求利润，_______，以次充好，严重损害了消费者的权益。填入画横线部分最恰当的是：',
    options: [
      { label: 'A', text: '掩耳盗铃' },
      { label: 'B', text: '偷工减料' },
      { label: 'C', text: '刻舟求剑' },
      { label: 'D', text: '守株待兔' },
    ],
    correctAnswer: 'B',
    explanation: '"偷工减料"指不按质量要求偷工减料，与后文"以次充好"构成并列关系，符合商家追求利润的语境。',
    linkedAngleId: 'a_4',
    linkedAngleName: '成语辨析',
    knowledgePath: '行测/言语理解与表达/逻辑填空/成语辨析',
    source: 'upload',
    createdAt: '2024-03-01',
  },

  // ===== 数量关系 - 数学运算 - 行程问题 (a_5) =====
  {
    id: 'qb_10',
    content: '甲乙两地相距300公里，一辆汽车从甲地出发，以每小时60公里的速度行驶，另一辆汽车同时从乙地出发，以每小时40公里的速度行驶，两车相向而行，几小时后相遇？',
    options: [
      { label: 'A', text: '2小时' },
      { label: 'B', text: '3小时' },
      { label: 'C', text: '4小时' },
      { label: 'D', text: '5小时' },
    ],
    correctAnswer: 'B',
    explanation: '相遇时间 = 路程 ÷ 速度和 = 300 ÷ (60+40) = 3小时。',
    images: ['https://placehold.co/600x400/e8f4f8/333?text=相遇问题示意图%0A甲车60km/h%0A←───────●───────→%0A300公里%0A←───────●───────→%0A乙车40km/h%0A相遇时间%3D300÷100%3D3小时'],
    linkedAngleId: 'a_5',
    linkedAngleName: '行程问题',
    knowledgePath: '行测/数量关系/数学运算/行程问题',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_11',
    content: '一列火车长200米，以每秒20米的速度通过一座长800米的桥，需要多少秒？',
    options: [
      { label: 'A', text: '40秒' },
      { label: 'B', text: '50秒' },
      { label: 'C', text: '60秒' },
      { label: 'D', text: '30秒' },
    ],
    correctAnswer: 'B',
    explanation: '通过桥的总距离 = 车长 + 桥长 = 200 + 800 = 1000米，时间 = 1000 ÷ 20 = 50秒。',
    linkedAngleId: 'a_5',
    linkedAngleName: '行程问题',
    knowledgePath: '行测/数量关系/数学运算/行程问题',
    source: 'upload',
    createdAt: '2024-02-20',
  },
  {
    id: 'qb_104',
    content: '甲、乙两人分别从A、B两地同时出发相向而行，甲每小时走5公里，乙每小时走4公里，两人相遇时甲比乙多走了3公里，则A、B两地相距多少公里？',
    options: [
      { label: 'A', text: '24公里' },
      { label: 'B', text: '27公里' },
      { label: 'C', text: '30公里' },
      { label: 'D', text: '33公里' },
    ],
    correctAnswer: 'B',
    explanation: '设相遇时间为t小时，则5t-4t=3，t=3小时。总路程=(5+4)×3=27公里。',
    linkedAngleId: 'a_5',
    linkedAngleName: '行程问题',
    knowledgePath: '行测/数量关系/数学运算/行程问题',
    source: 'upload',
    createdAt: '2024-03-05',
  },

  // ===== 数量关系 - 数学运算 - 工程问题 (a_6) =====
  {
    id: 'qb_12',
    content: '一项工程，甲单独做需12天完成，乙单独做需18天完成，两人合作几天可以完成？',
    options: [
      { label: 'A', text: '6天' },
      { label: 'B', text: '7.2天' },
      { label: 'C', text: '8天' },
      { label: 'D', text: '9天' },
    ],
    correctAnswer: 'B',
    explanation: '甲效率1/12，乙效率1/18，合作效率=1/12+1/18=5/36，时间=36/5=7.2天。',
    linkedAngleId: 'a_6',
    linkedAngleName: '工程问题',
    knowledgePath: '行测/数量关系/数学运算/工程问题',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_105',
    content: '一项工程，甲单独做需要20天完成，乙单独做需要30天完成。甲先单独做4天后，剩下的由甲乙合作完成，还需要多少天？',
    options: [
      { label: 'A', text: '8天' },
      { label: 'B', text: '9.6天' },
      { label: 'C', text: '10天' },
      { label: 'D', text: '12天' },
    ],
    correctAnswer: 'B',
    explanation: '甲4天完成4/20=1/5，剩余4/5。合作效率=1/20+1/30=5/60=1/12，还需(4/5)÷(1/12)=48/5=9.6天。',
    linkedAngleId: 'a_6',
    linkedAngleName: '工程问题',
    knowledgePath: '行测/数量关系/数学运算/工程问题',
    source: 'upload',
    createdAt: '2024-03-10',
  },

  // ===== 判断推理 - 图形推理 - 位置规律 (a_7) =====
  {
    id: 'qb_106',
    content: '在图形推理中，一组图形的每个小元素依次向右移动一格，到最右侧后从左侧出现，这属于哪种规律？',
    options: [
      { label: 'A', text: '平移规律' },
      { label: 'B', text: '旋转规律' },
      { label: 'C', text: '翻转规律' },
      { label: 'D', text: '叠加规律' },
    ],
    correctAnswer: 'A',
    explanation: '元素沿某一方向等距移动，到达边界后从另一侧出现，属于平移规律。这是位置规律中最基本的考查方式。',
    linkedAngleId: 'a_7',
    linkedAngleName: '位置规律',
    knowledgePath: '行测/判断推理/图形推理/位置规律',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_107',
    content: '九宫格图形推理中，第一行元素整体顺时针旋转90度得到第二行，第二行旋转90度得到第三行。这种规律属于：',
    options: [
      { label: 'A', text: '位置规律-平移' },
      { label: 'B', text: '位置规律-旋转' },
      { label: 'C', text: '样式规律-遍历' },
      { label: 'D', text: '属性规律-对称' },
    ],
    correctAnswer: 'B',
    explanation: '元素方向发生规律性变化（顺时针/逆时针旋转固定角度），属于位置规律中的旋转规律。',
    linkedAngleId: 'a_7',
    linkedAngleName: '位置规律',
    knowledgePath: '行测/判断推理/图形推理/位置规律',
    source: 'upload',
    createdAt: '2024-03-15',
  },

  // ===== 判断推理 - 逻辑判断 - 削弱论证 (a_8) =====
  {
    id: 'qb_108',
    content: '某研究显示，每天喝咖啡的人患心脏病的概率比不喝咖啡的人低20%。由此得出结论：喝咖啡有助于预防心脏病。以下哪项如果为真，最能削弱上述结论？',
    options: [
      { label: 'A', text: '喝咖啡的人往往更注重锻炼和饮食健康' },
      { label: 'B', text: '咖啡的种类不同，对心脏的影响也不同' },
      { label: 'C', text: '有些人喝咖啡后会出现心悸症状' },
      { label: 'D', text: '每天喝咖啡的人收入水平普遍较高' },
    ],
    correctAnswer: 'A',
    explanation: 'A项指出存在他因——喝咖啡的人本身更注重健康，可能是锻炼和饮食导致心脏病发病率低，属于"他因削弱"，最能削弱因果关系。',
    linkedAngleId: 'a_8',
    linkedAngleName: '削弱论证',
    knowledgePath: '行测/判断推理/逻辑判断/削弱论证',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_109',
    content: '某市实施限行政策后，交通拥堵指数下降了15%。有专家认为，限行政策有效缓解了交通拥堵。以下哪项如果为真，最能质疑该专家的观点？',
    options: [
      { label: 'A', text: '该市同期新增了3条地铁线路' },
      { label: 'B', text: '其他城市实施限行后效果不佳' },
      { label: 'C', text: '限行政策得到了市民的普遍支持' },
      { label: 'D', text: '该市交通事故率也在同期下降' },
    ],
    correctAnswer: 'A',
    explanation: 'A项指出地铁线路开通这一他因，可能是地铁而非限行缓解了拥堵，属于他因削弱。B项是类比削弱，力度弱于A项的他因削弱。',
    linkedAngleId: 'a_8',
    linkedAngleName: '削弱论证',
    knowledgePath: '行测/判断推理/逻辑判断/削弱论证',
    source: 'upload',
    createdAt: '2024-03-20',
  },

  // ===== 资料分析 - 增长率计算 - 同比/环比增长 (a_9) =====
  {
    id: 'qb_13',
    content: '某企业2023年利润为500万元，2022年为400万元，则利润同比增长：',
    options: [
      { label: 'A', text: '20%' },
      { label: 'B', text: '25%' },
      { label: 'C', text: '30%' },
      { label: 'D', text: '50%' },
    ],
    correctAnswer: 'B',
    explanation: '同比增长率=(500-400)/400×100%=25%。',
    images: ['https://placehold.co/600x400/dcfce7/333?text=同比增长率计算%0A2022年%3A400万元%0A↓%0A2023年%3A500万元%0A增长率%3D(500-400)÷400×100%25%3D25%25'],
    linkedAngleId: 'a_9',
    linkedAngleName: '同比/环比增长',
    knowledgePath: '行测/资料分析/增长量与增长率/同比/环比增长',
    source: 'practice',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_14',
    content: '某市2023年上半年GDP为8000亿元，同比增长8%，则2022年上半年GDP约为：',
    options: [
      { label: 'A', text: '7200亿元' },
      { label: 'B', text: '7407亿元' },
      { label: 'C', text: '7360亿元' },
      { label: 'D', text: '7600亿元' },
    ],
    correctAnswer: 'B',
    explanation: '基期值=现期值÷(1+增长率)=8000÷1.08≈7407亿元。',
    linkedAngleId: 'a_9',
    linkedAngleName: '同比/环比增长',
    knowledgePath: '行测/资料分析/增长量与增长率/同比/环比增长',
    source: 'upload',
    createdAt: '2024-03-01',
  },
  {
    id: 'qb_110',
    content: '某商品1月售价100元，2月售价105元，3月售价103元，则3月环比增长率为：',
    options: [
      { label: 'A', text: '3%' },
      { label: 'B', text: '-1.9%' },
      { label: 'C', text: '5%' },
      { label: 'D', text: '-2%' },
    ],
    correctAnswer: 'B',
    explanation: '环比增长率=(103-105)/105×100%≈-1.9%。环比是与上一期比较，3月环比是与2月比较。',
    linkedAngleId: 'a_9',
    linkedAngleName: '同比/环比增长',
    knowledgePath: '行测/资料分析/增长量与增长率/同比/环比增长',
    source: 'upload',
    createdAt: '2024-04-01',
  },

  // ===== 常识判断 - 政治常识 - 习近平新时代中国特色社会主义思想 (a_10) =====
  {
    id: 'qb_111',
    content: '习近平新时代中国特色社会主义思想明确，中国特色社会主义最本质的特征是：',
    options: [
      { label: 'A', text: '人民当家作主' },
      { label: 'B', text: '中国共产党领导' },
      { label: 'C', text: '公有制经济为主体' },
      { label: 'D', text: '依法治国' },
    ],
    correctAnswer: 'B',
    explanation: '习近平总书记明确指出，中国特色社会主义最本质的特征是中国共产党领导，这是习近平新时代中国特色社会主义思想的重要内容。',
    linkedAngleId: 'a_10',
    linkedAngleName: '习近平新时代中国特色社会主义思想',
    knowledgePath: '行测/常识判断/政治常识/习近平新时代中国特色社会主义思想',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_112',
    content: '党的二十大报告指出，从现在起，中国共产党的中心任务就是团结带领全国各族人民：',
    options: [
      { label: 'A', text: '实现中华民族伟大复兴' },
      { label: 'B', text: '全面建成社会主义现代化强国、实现第二个百年奋斗目标，以中国式现代化全面推进中华民族伟大复兴' },
      { label: 'C', text: '全面建设小康社会' },
      { label: 'D', text: '实现共同富裕' },
    ],
    correctAnswer: 'B',
    explanation: '党的二十大报告明确指出，从现在起，中国共产党的中心任务就是团结带领全国各族人民全面建成社会主义现代化强国、实现第二个百年奋斗目标，以中国式现代化全面推进中华民族伟大复兴。',
    linkedAngleId: 'a_10',
    linkedAngleName: '习近平新时代中国特色社会主义思想',
    knowledgePath: '行测/常识判断/政治常识/习近平新时代中国特色社会主义思想',
    source: 'upload',
    createdAt: '2024-04-05',
  },

  // ===== 常识判断 - 法律常识 - 宪法 (a_11) =====
  {
    id: 'qb_113',
    content: '根据我国宪法，中华人民共和国的一切权力属于：',
    options: [
      { label: 'A', text: '人民' },
      { label: 'B', text: '公民' },
      { label: 'C', text: '人民代表大会' },
      { label: 'D', text: '国家机关' },
    ],
    correctAnswer: 'A',
    explanation: '《宪法》第二条规定：中华人民共和国的一切权力属于人民。注意"人民"与"公民"的区别，人民是政治概念，公民是法律概念。',
    linkedAngleId: 'a_11',
    linkedAngleName: '宪法',
    knowledgePath: '行测/常识判断/法律常识/宪法',
    source: 'mindmap',
    createdAt: '2024-01-01',
  },
  {
    id: 'qb_114',
    content: '我国现行宪法是哪一年颁布的？',
    options: [
      { label: 'A', text: '1954年' },
      { label: 'B', text: '1975年' },
      { label: 'C', text: '1978年' },
      { label: 'D', text: '1982年' },
    ],
    correctAnswer: 'D',
    explanation: '我国现行宪法是1982年颁布的，又称"八二宪法"，至今已进行了5次修正（1988、1993、1999、2004、2018年）。',
    linkedAngleId: 'a_11',
    linkedAngleName: '宪法',
    knowledgePath: '行测/常识判断/法律常识/宪法',
    source: 'upload',
    createdAt: '2024-04-10',
  },
  {
    id: 'qb_115',
    content: '根据我国宪法规定，有权修改宪法的机关是：',
    options: [
      { label: 'A', text: '全国人民代表大会' },
      { label: 'B', text: '全国人民代表大会常务委员会' },
      { label: 'C', text: '国务院' },
      { label: 'D', text: '最高人民法院' },
    ],
    correctAnswer: 'A',
    explanation: '《宪法》第六十四条规定：宪法的修改，由全国人民代表大会常务委员会或者五分之一以上的全国人民代表大会代表提议，并由全国人民代表大会以全体代表的三分之二以上的多数通过。',
    linkedAngleId: 'a_11',
    linkedAngleName: '宪法',
    knowledgePath: '行测/常识判断/法律常识/宪法',
    source: 'upload',
    createdAt: '2024-04-15',
  },
];
